configfile: "../config/config.yaml"

import os
from glob import glob
from itertools import product
from fractions import Fraction

Dvalues = config["Dvalues"]
E_over_D_values = config["E_over_D_values"]
S_values = config["S_values"]
combos = list(product(S_values, E_over_D_values, Dvalues))
S_E_D_combinations = [(S, int(Fraction(E_over_D)*D), D) for (S, E_over_D, D) in combos]
allS, allE, allD = zip(*S_E_D_combinations)

Ln_wildcards = glob_wildcards("data/Bkq_{Ln}_real").Ln   # this will give a list of strings containing the lanthanides

rule all:
    input: 
        "results/suscplot/chi_ax_rh.png",
        expand("results/Ln/{Ln}/error_analysis_plot_{Ln}.png", Ln=Ln_wildcards),
        expand("results/Ln/{Ln}/h_plot_{Ln}.png", Ln=Ln_wildcards),
        expand("results/TM/S_{S}/E_{E}/D_{D}/error_analysis_plot_S_{S}_E_{E}_D_{D}.png", zip, S=allS, E=allE, D=allD),
        expand("results/TM/S_{S}/E_{E}/D_{D}/h_plot_S_{S}_E_{E}_D_{D}.png", zip, S=allS, E=allE, D=allD),
        "results/h_plot_TM_Ln_2in1.png",
        "results/TM/error_analysis_plot_2in1_1_0_6_2.5_0_6.png",    # 2in1 plot will not work for mixed positive and negative D! (because only one legend is displayed)
        "results/Ln/error_analysis_plot_2in1_Ho_Yb.png"

rule calc_susc_aniso:
    input:
        expand("data/Bkq_{Ln}_real", Ln=Ln_wildcards)
    output:
        "results/suscplot/Ln_list",
        "results/suscplot/chi_ax",
        "results/suscplot/chi_rh"
    shell:
        "julia scripts/susc_aniso.jl data {output} {Ln_wildcards}"

rule plot_chi_ax:
    input:
        "results/suscplot/Ln_list",
        "results/suscplot/chi_ax",
        "results/suscplot/chi_rh",
        "data/chi_ax_CASSCF",
        "data/chi_rh_CASSCF"
    output:
        "results/suscplot/chi_ax_rh.png"
    conda:
        "envs/matplotlib.yaml"
    shell:
        "python scripts/barplot_chi.py {input} {output}"

rule create_finitediff_functions:
    output:
        config['finitediff_file']
    params:
        stencil_size = config['stencil_size'],
        outfile = config['finitediff_file']
    shell:
        "julia scripts/create_finitediff_functions.jl {params.stencil_size} {params.outfile}"

rule TM_workflow:
    output:
        "results/TM/S_{S}/E_{E}/D_{D}/Dtensor_au.txt",
        "results/TM/S_{S}/E_{E}/D_{D}/T.txt"
    shell:
        "julia scripts/new_DTensor_func.jl {wildcards.D} {wildcards.E} {wildcards.S} {output[0]} {output[1]}"

rule calc_hnorms_Ln:
    input:
        "data/Bkq_{Ln}_real",
        last=config['finitediff_file']
    output:
        "results/Ln/{Ln}/h_norms.txt"
    params:
        h_minexp = config['h_minexp'],
        h_maxexp = config['h_maxexp']
    shell:
        "julia scripts/h_sans_beta_Ln.jl {params.h_minexp} {params.h_maxexp} {input.last} {wildcards.Ln} {output}"

rule calc_hnorms_TM:
    input:
        "results/TM/S_{S}/E_{E}/D_{D}/Dtensor_au.txt",
        last=config['finitediff_file']
    output:
        "results/TM/S_{S}/E_{E}/D_{D}/h_norms.txt"
    params:
        h_minexp = config['h_minexp'],
        h_maxexp = config['h_maxexp']
    shell:
        "julia scripts/h_sans_beta_TM.jl {params.h_minexp} {params.h_maxexp} {input.last} {input[0]} {wildcards.S} {output}"

rule h_plot_TM:
    input:
        "results/TM/S_{S}/E_{E}/D_{D}/h_norms.txt"
    output:
        "results/TM/S_{S}/E_{E}/D_{D}/h_plot_S_{S}_E_{E}_D_{D}.png"
    conda:
        "envs/matplotlib.yaml"
    params:
        h_minexp = config['h_minexp'],
        h_maxexp = config['h_maxexp']
    shell:
        "python scripts/h_plots.py {params.h_minexp} {params.h_maxexp} {input} {output}"

rule h_plot_Ln:
    input:
        "results/Ln/{system}/h_norms.txt"
    output:
        "results/Ln/{system}/h_plot_{system}.png"
    conda:
        "envs/matplotlib.yaml"
    params:
        h_minexp = config['h_minexp'],
        h_maxexp = config['h_maxexp']
    shell:
        "python scripts/h_plots.py {params.h_minexp} {params.h_maxexp} {input} {output}"

rule h_plot_2in1:
    input:
        "results/TM/S_1/E_0/D_6/h_norms.txt",
        "results/Ln/Yb/h_norms.txt"
    output:
        "results/h_plot_TM_Ln_2in1.png"
    conda:
        "envs/matplotlib.yaml"
    params:
        h_minexp = config['h_minexp'],
        h_maxexp = config['h_maxexp']
    shell:
        "python scripts/h_plots_2in1.py {params.h_minexp} {params.h_maxexp} {input} {output}"

rule optimize_h:
    input:
        "results/{folder}/h_norms.txt"
    output:
        "results/{folder}/optimal_h_value.txt",
    params:
        h_minexp = config['h_minexp'],
        h_maxexp = config['h_maxexp']
    shell:
        "python scripts/optimal_hvalues.py {params.h_minexp} {params.h_maxexp} {input} {output}"

rule calc_run_Ln:
    input:
        "data/Bkq_{Ln}_real",
        h = "results/Ln/{Ln}/optimal_h_value.txt",
        last=config['finitediff_file']
    output:
        "results/Ln/{Ln}/diff_norms.txt"
    params:
        Tmin = config['Ln_Tmin'],
        Tmax = config['Ln_Tmax'],
        Tinterval = config['Ln_Tinterval']
    shell:
        "julia scripts/dyadics_Ln.jl {params.Tmin} {params.Tmax} {params.Tinterval} {input.h} {input.last} {wildcards.Ln} {output}"

rule calc_run_TM:
    input:
        "results/TM/S_{S}/E_{E}/D_{D}/Dtensor_au.txt",
        "results/TM/S_{S}/E_{E}/D_{D}/T.txt",
        "results/TM/S_{S}/E_{E}/D_{D}/optimal_h_value.txt",
        last=config['finitediff_file']
    output:
        "results/TM/S_{S}/E_{E}/D_{D}/diff_norms.txt"
    shell:
        "julia scripts/dyadics_TM.jl {input[0]} {wildcards.S} {input[1]} {input[2]} {input[3]} {output}"

rule dyadic_plot_Ln:
    input:
        "results/Ln/{system}/diff_norms.txt"
    output:
        "results/Ln/{system}/error_analysis_plot_{system}.png"
    conda:
        "envs/matplotlib.yaml"
    params:
        Tmin = config['Ln_Tmin'],
        Tmax = config['Ln_Tmax'],
        Tinterval = config['Ln_Tinterval']
    shell:
        "python scripts/errorplot_Ln.py {params.Tmin} {params.Tmax} {params.Tinterval} {input} {wildcards.system} {output}"

rule dyadic_plot_Ln_2in1:
    input:
        "results/Ln/{ln1}/diff_norms.txt",
        "results/Ln/{ln2}/diff_norms.txt"
    output:
        "results/Ln/error_analysis_plot_2in1_{ln1}_{ln2}.png"
    conda:
        "envs/matplotlib.yaml"
    params:
        Tmin = config['Ln_Tmin'],
        Tmax = config['Ln_Tmax'],
        Tinterval = config['Ln_Tinterval']
    shell:
        "python scripts/errorplot_Ln_2in1.py {params.Tmin} {params.Tmax} {params.Tinterval} {input[0]} {wildcards.ln1} {input[1]} {wildcards.ln2} {output}"

rule dyadic_plot_TM:
    input:
        "results/TM/S_{S}/E_{E}/D_{D}/diff_norms.txt",
        "results/TM/S_{S}/E_{E}/D_{D}/T.txt"
    output:
        "results/TM/S_{S}/E_{E}/D_{D}/error_analysis_plot_S_{S}_E_{E}_D_{D}.png"
    conda:
        "envs/matplotlib.yaml"
    shell:
        "python scripts/errorplot_TM.py {wildcards.S} {wildcards.E} {wildcards.D} {input[0]} {input[1]} {output}"

rule dyadic_plot_TM_2in1:
    input:
        "results/TM/S_{S1}/E_{E1}/D_{D1}/diff_norms.txt",
        "results/TM/S_{S1}/E_{E1}/D_{D1}/T.txt",
        "results/TM/S_{S2}/E_{E2}/D_{D2}/diff_norms.txt",
        "results/TM/S_{S2}/E_{E2}/D_{D2}/T.txt"
    output:
        "results/TM/error_analysis_plot_2in1_{S1}_{E1}_{D1}_{S2}_{E2}_{D2}.png"
    conda:
        "envs/matplotlib.yaml"
    shell:
        "python scripts/errorplot_TM_2in1.py {wildcards.S1} {wildcards.E1} {wildcards.D1} {input[0]} {input[1]} {wildcards.S2} {wildcards.E2} {wildcards.D2} {input[2]} {input[3]} {output}"
