stencil_size: 12
finitediff_file: "results/finitediff_functions.jl"
Ln_Tmin: 100
Ln_Tmax: 500
Ln_Tinterval: 50
h_minexp: -1
h_maxexp: 4
Dvalues: [-6, 6, 60]    # D values and E/D values should be chosen such that all D and E values are integer
E_over_D_values: [0, 1/6, 1/3]
S_values: [1, 1.5, 2, 2.5]
